
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # mount nginx configuration to nginx container
      - ./conf.d:/etc/nginx/conf.d:ro # mount all server block configurations to nginx container
      - ./ssl:/etc/nginx/ssl:ro # mount ssl file to nginx container  ssl folder
      - ./logs:/var/log/nginx # store logs in host folder
      - ./cache:/var/cache/nginx # store the cache in host folder
      - ../websites:/var/www # mount all websites
      - phpmyadmin_data:/var/www/html:ro # mount phpmyadmin volume to nginx
    environment:
      - LC_TIME=en_US.UTF-8
      - LANG=en_US.UTF-8
      - TZ=Asia/Manila
    networks:
      - web-network
    deploy:
      resources:
        limits:
          memory: '256m'
          cpus: '0.25'
        reservations:
          cpus: '0.1'     # Reserve minimum CPU
          memory: '128m'  # Reserve minimum memory


networks:
  web-network:
    external: true

volumes:
  phpmyadmin_data:
    external: true
